server:
  port: 10010
spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: user-service-route
          uri: lb://user-service
          predicates:
            - Path=/**
          filters:
            - PrefixPath=/user
      default-filters:
        - AddResponseHeader=i-love,heima
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka