server:
  port: 8080
spring:
  application:
    name: consumer-service
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
# 修改服务地址轮询策略，默认是轮询，配置之后变随机
# RandomRule 随机
# RoundRobinRule 轮询策略
user-service:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
feign:
  hystrix:
    enabled: true # 开启Feign的熔断功能

# 配置日志信息
logging:
  level:
    com.itheima: debug

#hystrix:
#  command:
#    default:
#      circuitBreaker:
#        # 原理分析中解释配置含义 # 强制打开熔断器 默认false关闭的。测试配置是否生效
#        forceOpen: false
#        # 触发熔断错误比例阈值，默认值50%
#        errorThresholdPercentage: 50
#        # 熔断后休眠时长，默认值5秒
#        sleepWindowInMilliseconds: 20000
#        # 熔断触发最小请求次数，默认值是20
#        requestVolumeThreshold: 10
#      execution:
#          isolation:
#            thread:
#              # 熔断超时设置，默认为1秒
#              timeoutInMilliseconds: 2000
